#!/bin/bash
python -m attributions.compute_attributions --load_from=checkpoints/ff_layer_jsae_0.0ep00 --save_to=attributions/data --data_dir=data/shakespeare --save_name=ff_layer_jsae_0.0ep00 --num_batches=24 --batch_size=24 --steps=4 --attribution_method=ig
python -m attributions.compute_attributions --load_from=checkpoints/ff_layer_jsae_1.0e-03 --save_to=attributions/data --data_dir=data/shakespeare --save_name=ff_layer_jsae_1.0e-03 --num_batches=24 --batch_size=24 --steps=4 --attribution_method=ig
python -m attributions.compute_attributions --load_from=checkpoints/ff_layer_jsae_1.2e-03 --save_to=attributions/data --data_dir=data/shakespeare --save_name=ff_layer_jsae_1.2e-03 --num_batches=24 --batch_size=24 --steps=4 --attribution_method=ig
python -m attributions.compute_attributions --load_from=checkpoints/ff_layer_jsae_1.5e-03 --save_to=attributions/data --data_dir=data/shakespeare --save_name=ff_layer_jsae_1.5e-03 --num_batches=24 --batch_size=24 --steps=4 --attribution_method=ig
python -m attributions.compute_attributions --load_from=checkpoints/ff_layer_jsae_1.8e-03 --save_to=attributions/data --data_dir=data/shakespeare --save_name=ff_layer_jsae_1.8e-03 --num_batches=24 --batch_size=24 --steps=4 --attribution_method=ig
python -m attributions.compute_attributions --load_from=checkpoints/ff_layer_jsae_2.2e-03 --save_to=attributions/data --data_dir=data/shakespeare --save_name=ff_layer_jsae_2.2e-03 --num_batches=24 --batch_size=24 --steps=4 --attribution_method=ig
python -m attributions.compute_attributions --load_from=checkpoints/ff_layer_jsae_2.7e-03 --save_to=attributions/data --data_dir=data/shakespeare --save_name=ff_layer_jsae_2.7e-03 --num_batches=24 --batch_size=24 --steps=4 --attribution_method=ig
python -m attributions.compute_attributions --load_from=checkpoints/ff_layer_jsae_3.3e-03 --save_to=attributions/data --data_dir=data/shakespeare --save_name=ff_layer_jsae_3.3e-03 --num_batches=24 --batch_size=24 --steps=4 --attribution_method=ig
python -m attributions.compute_attributions --load_from=checkpoints/ff_layer_jsae_3.9e-03 --save_to=attributions/data --data_dir=data/shakespeare --save_name=ff_layer_jsae_3.9e-03 --num_batches=24 --batch_size=24 --steps=4 --attribution_method=ig
python -m attributions.compute_attributions --load_from=checkpoints/ff_layer_jsae_4.7e-03 --save_to=attributions/data --data_dir=data/shakespeare --save_name=ff_layer_jsae_4.7e-03 --num_batches=24 --batch_size=24 --steps=4 --attribution_method=ig
python -m attributions.compute_attributions --load_from=checkpoints/ff_layer_jsae_5.6e-03 --save_to=attributions/data --data_dir=data/shakespeare --save_name=ff_layer_jsae_5.6e-03 --num_batches=24 --batch_size=24 --steps=4 --attribution_method=ig
python -m attributions.compute_attributions --load_from=checkpoints/ff_layer_jsae_6.8e-03 --save_to=attributions/data --data_dir=data/shakespeare --save_name=ff_layer_jsae_6.8e-03 --num_batches=24 --batch_size=24 --steps=4 --attribution_method=ig
python -m attributions.compute_attributions --load_from=checkpoints/ff_layer_jsae_1.0e-02 --save_to=attributions/data --data_dir=data/shakespeare --save_name=ff_layer_jsae_1.0e-02 --num_batches=24 --batch_size=24 --steps=4 --attribution_method=ig